module.exports = {
  User: require('./User'),
  Gym: require('./Gym'),
  MembershipPlan: require('./MembershipPlan'),
  Membership: require('./Membership'),
  Attendance: require('./Attendance'),
  Exercise: require('./Exercise'),
  WorkoutPlan: require('./WorkoutPlan'),
  WorkoutLog: require('./WorkoutLog'),
  DietPlan: require('./DietPlan'),
  TrainerProfile: require('./TrainerProfile'),
  GymTrainer: require('./GymTrainer'),
  GymStaffMember: require('./GymStaffMember'),
  TrainerBooking: require('./TrainerBooking'),
  Product: require('./Product'),
  Order: require('./Order'),
  Payment: require('./Payment'),
  ChatConversation: require('./ChatConversation'),
  Notification: require('./Notification'),
  RefreshToken: require('./RefreshToken'),
  GymReview: require('./GymReview'),
};